#!/bin/bash
# MCE_LEMP change password
# Version: 1.0
# Author: mbrother

source /var/mce/script/variable_common
source ${BASH_DIR}/lang
[[ -f /var/mce/custom/lang ]] && source /var/mce/custom/lang

# Print ─
printf_c(){
    if [ $1 -le 0 ]
    then
        echo ""
    else
        printf '%0.s─' $(seq 1 $1)
    fi
}

# Check user exist or not
check_user() {
    CHECK_USER1=`ls ${USER_DIR} | wc -l`
    [[ ${CHECK_USER1} -eq 0 ]] && exit
    false
    while [ $? -eq 1 ]
    do
        read -p " ${LANG_CHANGE_PASSWORD1} " USER
        ${BASH_DIR}/check_value name "${USER}"
        if [ $? -eq 1 ]
        then
            echo -e "${RED}${LANG_CHANGE_PASSWORD2}${REMOVE}"
            false
        fi
    done
    CHECK_USER2=`ls -1 ${USER_DIR} | grep -cx ${USER}`
    if [ ${CHECK_USER2} -eq 0 ]
    then
        echo -e "${RED}${LANG_CHANGE_PASSWORD3} ${USER} ${LANG_CHANGE_PASSWORD4}${REMOVE}"
        check_user
    fi
}

# Check connect to mysql
check_mysql(){
    CHECK_MYSQL=`mysql -e "SHOW DATABASES;" | wc -l`
    if [ ${CHECK_MYSQL} -eq 0 ]
    then
        echo ""
        echo -e "${RED}${LANG_CHANGE_PASSWORD5}${REMOVE}"
        echo -e "${RED}${LANG_CHANGE_PASSWORD6}${REMOVE}"
        exit
    fi
}

# Check user database name
check_user_db(){
    false
    while [ $? -eq 1 ]
    do
        read -p " ${LANG_CHANGE_PASSWORD7} " DB_USER
        ${BASH_DIR}/check_value name "${DB_USER}"
        if [ $? -eq 1 ]
        then
            echo -e "${RED}${LANG_CHANGE_PASSWORD8}${REMOVE}"
            false
        fi
    done
    CHECK_DB_USER=`cat ${USER_DIR}/*/db | cut -d":" -f2 | grep -cx ${DB_USER}`
    if [ ${CHECK_DB_USER} -eq 0 ]
    then
        echo -e "${RED}${LANG_CHANGE_PASSWORD9} ${DB_USER} ${LANG_CHANGE_PASSWORD10}${REMOVE}"
        check_user_db
    fi
}

# Generate random password
random_pwd(){
    read -p " ${LANG_CHANGE_PASSWORD11} " NEW_PASS1
    if [ -z ${NEW_PASS1} ]
    then
        NEW_PASS2=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-12}`
    else
        NEW_PASS2=${NEW_PASS1}
    fi
}

# Change root's password of server
change_root_pwd(){
    random_pwd
    echo "${NEW_PASS2}" | passwd root --stdin >> /dev/null
    echo -e " ${GREEN}${LANG_CHANGE_PASSWORD12}${REMOVE}"
    [[ -z ${NEW_PASS1} ]] && echo -e " ${LANG_CHANGE_PASSWORD13} ${GREEN}${NEW_PASS2}${REMOVE}"
}

# Change FPT password for user
change_ftp_pwd(){
    ${BASH_DIR}/show_info USER
    check_user
    random_pwd
    echo "${NEW_PASS2}" | passwd ${USER} --stdin >> /dev/null
    NEW_PASS2_PWD=`cat /etc/shadow | grep -w "${USER}" | cut -d":" -f2`
    echo "${NEW_PASS2_PWD}" > ${USER_DIR}/"${USER}"/pwd
    echo -e "${GREEN} ${LANG_CHANGE_PASSWORD14} ${USER}${REMOVE}"
    [[ -z ${NEW_PASS1} ]] && echo -e " ${LANG_CHANGE_PASSWORD15} ${GREEN}${NEW_PASS2}${REMOVE}"
}

change_mysql_pwd(){
    check_mysql
    ${BASH_DIR}/show_info DATABASE
    if [ $(ls ${USER_DIR} | wc -l) -eq 0 ]
    then
        exit
    elif [ $(cat ${USER_DIR}/*/db | wc -l) -eq 0 ]
    then
        exit
    fi
    check_user_db
    random_pwd
    MYSQL=`which mysql`
    Q1="USE mysql;"
    Q2="UPDATE mysql.user SET Password=PASSWORD('${NEW_PASS2}') WHERE USER='${DB_USER}';"
    Q3="FLUSH PRIVILEGES;"
    SQL="${Q1}${Q2}${Q3}"
    ${MYSQL} -e "${SQL}"
    USER=`echo ${DB_USER} | cut -d"_" -f1`
    USER_DB_PWD_PWD=`mysql -e "SELECT user,password FROM mysql.user;" | grep ${DB_USER} | awk '{print $2}'`
    sed -i "s|${DB_USER}:.*|${DB_USER}:${USER_DB_PWD_PWD}|" ${USER_DIR}/${USER}/db
    echo -e "${GREEN} ${LANG_CHANGE_PASSWORD16} ${DB_USER}${REMOVE}"
    [[ -z ${NEW_PASS1} ]] && echo -e " ${LANG_CHANGE_PASSWORD17} ${GREEN}${NEW_PASS2}${REMOVE}"
}

echo " ${LANG_CHANGE_PASSWORD18}"
echo " ${LANG_CHANGE_PASSWORD19}"
echo " ${LANG_CHANGE_PASSWORD20}"
echo " ${LANG_CHANGE_PASSWORD21}"
echo " ${LANG_CHANGE_PASSWORD22}"
false
while [ $? -eq 1 ]
do
    read -p " ${LANG_CHANGE_PASSWORD23} " CHOICE
    ${BASH_DIR}/check_value number "${CHOICE}" 3
    if [ $? -eq 1 ]
    then
        echo -e "${RED} ${LANG_CHANGE_PASSWORD24} 3${REMOVE}"
        false
    fi
done

case ${CHOICE} in
    1) change_root_pwd;;
    2) change_ftp_pwd;;
    3) change_mysql_pwd;;
esac
