#!/bin/bash
# MCE_LEMP download all scripts of mce
# Version: 1.0
# Author: mbrother

# Set variable
GREEN='\e[92m'
RED='\e[31m'
REMOVE='\e[0m'
BASH_DIR="/var/mce/script"
USER_DIR="/var/mce/user"
GITHUB_LINK="https://raw.githubusercontent.com/mbrother2/buildmce/master/script"

# Create directory if not exist
if [ ! -d ${BASH_DIR} ]
then
    mkdir -p ${BASH_DIR}
fi
if [ ! -d ${USER_DIR} ]
then
    mkdir -p ${USER_DIR}
fi

# Download script
for i in advanced_option \
         auto_backup \
         backup_full \
         backup_user \
         change_domain \
         change_language \
         change_password \
         change_php_version \
         check_service \
         check_value \
         clear_cache \
         create_database \
         create_full \
         create_ssl_letsencrypt \
         create_swap \
         delete_user \
         mce \
         rotate_log \
         restore_backup \
         show_info \
         update_service \
         variable_common
do
    curl -so ${BASH_DIR}/$i ${GITHUB_LINK}/$i
    chmod 755 ${BASH_DIR}/$i
    echo ""
done | pv -peWs22 >/dev/null
ln -sf ${BASH_DIR}/mce /usr/sbin/mce
echo "0 0 1 * * /var/mce/script/rotate_log" >> /var/spool/cron/root