#!/bin/bash
# MCE_LEMP clear cache nginx
# Version: 1.0
# Author: mbrother

source /var/mce/script/variable_common
source ${BASH_DIR}/lang
[[ -f /var/mce/custom/lang ]] && source /var/mce/custom/lang

# Print ─
printf_c(){
    if [ $1 -le 0 ]
    then
        echo ""
    else
        printf '%0.s─' $(seq 1 $1)
    fi
}

# Print domains
print_domain(){
    echo    " ┌─`printf_c ${#LANG_CLEAR_CACHE1}`─┐"
    echo -e " │ ${GREEN}${LANG_CLEAR_CACHE1}${REMOVE} │"
    echo    " └─`printf_c ${#LANG_CLEAR_CACHE1}`─┘"
    ls -1 ${USER_DIR} > /tmp/all_users
    VAR_TMP=1
    rm -f /tmp/all_domains
    for i in $(cat /tmp/all_users)
    do
        echo " ${VAR_TMP}. ${i} `cat ${USER_DIR}/${i}/domain`" >> /tmp/all_domains
        VAR_TMP=$[ ${VAR_TMP} + 1 ]
    done
    cat /tmp/all_domains | awk '{print $1 " " $3}'
}

if [ -z "$(ls ${USER_DIR})" ]
then
    echo -e "${RED}${LANG_CLEAR_CACHE2}${REMOVE}"
    exit
fi

if [ $(ls ${USER_DIR} | wc -l) -ge 1 ]
then
    if [ -z "$(ls ${USER_DIR}/* | grep domain)" ]
    then
        echo -e "${RED}${LANG_CLEAR_CACHE2}${REMOVE}"
        exit
    else
        print_domain
        false
        while [ $? -eq 1 ]
        do
            DOMAIN_COUNT=`ls ${USER_DIR}/*/ | grep domain | wc -l`
            read -p  "${LANG_CLEAR_CACHE3} " CHOICE
            ${BASH_DIR}/check_value number "${CHOICE}" "${DOMAIN_COUNT}"
            if [ $? -eq 1 ]
            then
                echo -e "${RED}${LANG_CLEAR_CACHE4} ${DOMAIN_COUNT}!${REMOVE}"
                false
            fi
        done
        USER=`cat /tmp/all_domains | awk -v CHOICE2="${CHOICE}""."  '{if (CHOICE2 == $1) print $2}'`
        if [[ ! -d ${CACHE_DIR}/${USER} ]] || [[ -z $(ls ${CACHE_DIR}/${USER}) ]]
        then
            echo -e "${RED}${LANG_CLEAR_CACHE5}${REMOVE}"
        else
            cd ${CACHE_DIR}/${USER}
            rm -rf *
            if [ -f /bin/systemctl ]
            then
                systemctl restart nginx
            else
                service nginx restart
            fi
            echo -e "${GREEN}${LANG_CLEAR_CACHE6}${REMOVE}"
        fi
    fi
fi

rm -f /tmp/all_users
rm -f /tmp/all_domains
